In [34]:
# Task 1: Data Cleaning and Preprocessing
# -> Load the dataset using pandas.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
df = pd.read_csv("D:/Codveda Technologies project/Umair-L1-TASK1 Datacleanng and preprocessing/1) iris.csv")

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [37]:
df.shape

(150, 5)

In [38]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [39]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [40]:
# 2.Identify and handle missing values
df . isnull().sum()/len(df)*100

sepal_length    0.0
sepal_width     0.0
petal_length    0.0
petal_width     0.0
species         0.0
dtype: float64

In [41]:
# 3.Remove duplicate rows and standardize inconsistent data formats

df.duplicated().sum()   #check duplicates

np.int64(3)

In [42]:
df[df.duplicated()]

     sepal_length  sepal_width  petal_length  petal_width    species
34            4.9          3.1           1.5          0.1     setosa
37            4.9          3.1           1.5          0.1     setosa
142           5.8          2.7           5.1          1.9  virginica

In [43]:
df = df.drop_duplicates() #drop the duplicates

In [44]:
df.duplicated().sum()

np.int64(0)

In [45]:
df.shape #recheck the dataset

(147, 5)

In [46]:
# finding categorical values as in this dataset there is no column called date section.

df["species"].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [47]:
df['species'] = df['species'].str.strip().str.lower()

In [48]:
df['species'].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [49]:
df['species'] = df['species'].astype('category')

In [50]:
print(df['species'].value_counts())
print(df['species'].unique())
print(df.dtypes)

species
versicolor    50
virginica     49
setosa        48
Name: count, dtype: int64
['setosa', 'versicolor', 'virginica']
Categories (3, str): ['setosa', 'versicolor', 'virginica']
sepal_length     float64
sepal_width      float64
petal_length     float64
petal_width      float64
species         category
dtype: object