In [13]:
import pandas as pd

df = pd.read_csv("D:/Codveda Technologies project/Umair-L2-TASK 1 Regression Analysis/4) house Prediction Data Set.csv")

df = pd.read_csv("4) house Prediction Data Set.csv", sep=r'\s+', header=None)

In [14]:
df . head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [15]:
df . shape

(506, 14)

In [16]:
# changing column names in more readable format

df.columns = [
    'crime_rate',
    'residential_land',
    'industrial_land',
    'river_proximity',
    'nitric_oxide',
    'average_rooms',
    'older_homes',
    'employment_distance',
    'highway_access',
    'property_tax',
    'pupil_teacher_ratio',
    'black_population_index',
    'lower_status_population',
    'house_value'
]

In [17]:
print(df.shape)

(506, 14)

In [18]:
df.head()

,crime_rate,residential_land,industrial_land,river_proximity,nitric_oxide,average_rooms,older_homes,employment_distance,highway_access,property_tax,pupil_teacher_ratio,black_population_index,lower_status_population,house_value
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [19]:
df.info

<bound method DataFrame.info of      crime_rate  residential_land  industrial_land  river_proximity  \
0       0.00632              18.0             2.31                0
1       0.02731               0.0             7.07                0
2       0.02729               0.0             7.07                0
3       0.03237               0.0             2.18                0
4       0.06905               0.0             2.18                0
..          ...               ...              ...              ...
501     0.06263               0.0            11.93                0
502     0.04527               0.0            11.93                0
503     0.06076               0.0            11.93                0
504     0.10959               0.0            11.93                0
505     0.04741               0.0            11.93                0

     nitric_oxide  average_rooms  older_homes  employment_distance  \
0           0.538          6.575         65.2               4.0900
1           0.469          6.421         78.9               4.9671
2           0.469          7.185         61.1               4.9671
3           0.458          6.998         45.8               6.0622
4           0.458          7.147         54.2               6.0622
..            ...            ...          ...                  ...
501         0.573          6.593         69.1               2.4786
502         0.573          6.120         76.7               2.2875
503         0.573          6.976         91.0               2.1675
504         0.573          6.794         89.3               2.3889
505         0.573          6.030         80.8               2.5050

     highway_access  property_tax  pupil_teacher_ratio  \
0                 1         296.0                 15.3
1                 2         242.0                 17.8
2                 2         242.0                 17.8
3                 3         222.0                 18.7
4                 3         222.0                 18.7
..              ...           ...                  ...
501               1         273.0                 21.0
502               1         273.0                 21.0
503               1         273.0                 21.0
504               1         273.0                 21.0
505               1         273.0                 21.0

     black_population_index  lower_status_population  house_value
0                    396.90                     4.98         24.0
1                    396.90                     9.14         21.6
2                    392.83                     4.03         34.7
3                    394.63                     2.94         33.4
4                    396.90                     5.33         36.2
..                      ...                      ...          ...
501                  391.99                     9.67         22.4
502                  396.90                     9.08         20.6
503                  396.90                     5.64         23.9
504                  393.45                     6.48         22.0
505                  396.90                     7.88         11.9

[506 rows x 14 columns]>

In [20]:
df.isnull().sum()

crime_rate                 0
residential_land           0
industrial_land            0
river_proximity            0
nitric_oxide               0
average_rooms              0
older_homes                0
employment_distance        0
highway_access             0
property_tax               0
pupil_teacher_ratio        0
black_population_index     0
lower_status_population    0
house_value                0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.describe()

,crime_rate,residential_land,industrial_land,river_proximity,nitric_oxide,average_rooms,older_homes,employment_distance,highway_access,property_tax,pupil_teacher_ratio,black_population_index,lower_status_population,house_value
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [ ]:
# creating x and y values

X = df.drop('house_value', axis=1)
y = df['house_value']

print(X.shape)
print(y.shape)

(506, 13)
(506,)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (404, 13)
X_test: (102, 13)
y_train: (404,)
y_test: (102,)

In [32]:
# 2. Fit a linear regression model using scikit-learn

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

print("model trained successfully")

model trained successfully

In [35]:
# 3.Interpret the coefficients and evaluate the model using metrics such as R-squared and mean squared error.

print("Intercept:", model.intercept_)
coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_
})

print(coefficients)


y_pred = model.predict(X_test)

# R-squared and mean squared error

from sklearn.metrics import r2_score, mean_squared_error

r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R-squared:", r2)
print("Mean Squared Error:", mse)

Intercept: 30.24675099392349
                    Feature  Coefficient
0                crime_rate    -0.113056
1          residential_land     0.030110
2           industrial_land     0.040381
3           river_proximity     2.784438
4              nitric_oxide   -17.202633
5             average_rooms     4.438835
6               older_homes    -0.006296
7       employment_distance    -1.447865
8            highway_access     0.262430
9              property_tax    -0.010647
10      pupil_teacher_ratio    -0.915456
11   black_population_index     0.012351
12  lower_status_population    -0.508571
R-squared: 0.6687594935356317
Mean Squared Error: 24.291119474973538